spring:
  redis:
    port: 6379
    host: host.docker.internal
  jwt:
    secret: goodbye2024hi2025hichristmas2024

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
    exchange: chat.exchange
    queue: chat.queue
    routing: '*.room.*'

  data:
    mongodb:
      uri: mongodb://testuser:testuser@localhost:27017/test


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.example.demo.config.UpperCaseSnakeCaseNamingStrategy # 네이밍 설정
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace # 물음표 바인딩 출력되도록

server:
  port: 8083